name: AES Aben
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/AES-Aben
license: GPL-3.0-or-later
version: 5th May 2021
shortDescription: Fills in space in the galaxy with a new alien species.
description: New aliens that are incapable of spaceflight as far as the player is
  concerned, offers the player multiple missions in aiding the Aben which also
  benefit the player in turn.
url: https://github.com/Adde-Endless-Sky/AES-Aben/archive/3f569b3bf386981773b6a21b88542c039f5f5153.zip
iconUrl: https://raw.githubusercontent.com/Adde-Endless-Sky/AES-Aben/master/icon.png
autoupdate:
  type: tag
  url: https://github.com/endless-sky/all-content-plugin/archive/refs/tags/$version.zip
  iconUrl: https://github.com/endless-sky/all-content-plugin/raw/$version/icon.png
